% create a sequence of events generated by a Poisson Process
% INPUT:
%   lambda: parameter of the Poisson process
%   timeLength: time length
% OUTPUT:
%   eventTimes: sequence of event times

function eventTimes = poissonProcess(lambda, timeLength)

R = poissrnd(lambda * timeLength);

% generate R events
r = zeros(R,1);
for i = 1:R
    r(i) = rand() * timeLength;
end

% sort event times
eventTimes = sort(r);

end
